### ISSUE TITLE
Probeer dit in de view al te doen

### ISSUE THREAD

**Issue by krijnhoetmer** [RickVellingaa/toolboard-vervoer-sprint-2#3]
Client-side JS is helaas niet de juiste plek :) Net laten zien hoe je dit met view parameters en een if statement in je EJS kunt doen.

https://github.com/RickVellingaa/toolboard-vervoer-sprint-2/blob/e2044937488554a8cd60a3ce8320a840958edac3/public/script.js#L38-L44

**Comment by RickVellingaa** [comment]
Gedaan :)
